task :default => :tu

desc "Pruebas unitarias de la clase Matrices"
task :tu do
  sh "ruby -I. test/tc_matrices.rb"
end

desc "Ejecutar solo las pruebas simples"
task :simple do
  sh "ruby -I. test/tc_matrices.rb -n /simple/"
end