require "bundler/gem_tasks"
require "rspec/core/rake_task"

RSpec::Core::RakeTask.new(:spec)

task :default => :spec

desc "Pruebas con formato extendido"
task :doc do
  sh "rspec spec/granja_spec.rb --format doc"
  sh "rspec spec/funcion_spec.rb --format doc"
  sh "rspec spec/datos_spec.rb --format doc"
  sh "rspec spec/animal_spec.rb --format doc"
  sh "rspec spec/ave_spec.rb --format doc"
end